"""Diagnostic: what BARO ranks first on RE2-OB/SS (reference runs), and how the RE1/RE2 reduced tables differ.
Reads the stored run outputs (runs/baro/baro_re{1,2}-*_len20.json) and one case table per subsystem.
Run on the 3090 merged workspace; writes paper/data/supp/baro_re2_top1.json (diagnostic data, not regenerated by the analysis pipeline). Does not read the frozen long table."""
import collections, glob, hashlib, json, os, sys
import pandas as pd
R = os.path.expanduser("$AUDIT_ROOT/runs/baro")
DATA = os.path.expanduser("~/rcaeval_repo/data")
out = {"source": "runs/baro/baro_re{1,2}-{ob,ss,tt}_len20.json; first case table of each subsystem", "runs": {}, "tables": {}}
for rel in ("re1", "re2"):
    for s in ("ob", "ss", "tt"):
        f = f"{R}/baro_{rel}-{s}_len20.json"
        d = json.load(open(f)); cs = d["cases"]
        top1 = collections.Counter(c["ranks"][0] for c in cs if c["ranks"])
        out["runs"][f"{rel}-{s}"] = {"file": os.path.relpath(f, os.path.expanduser("$AUDIT_ROOT")), "sha256": hashlib.sha256(open(f, "rb").read()).hexdigest()[:16],
            "n": d["n"], "acc1": round(d["acc1"], 4), "acc3": round(d["acc3"], 4), "acc5": round(d["acc5"], 4), "coverage": d["coverage"],
            "input_file": d["config"].get("input_file") or d.get("file"), "top1_most_common": top1.most_common(3),
            "n_cols_min": min(c["n_cols"] for c in cs), "n_cols_max": max(c["n_cols"] for c in cs)}
pats = {"re1-ob": f"{DATA}/online-boutique/*/1/data.csv", "re1-ss": f"{DATA}/sock-shop-2/*/1/simple_data.csv", "re1-tt": f"{DATA}/train-ticket/*/1/simple_data.csv",
        "re2-ob": f"{DATA}/RE2/RE2-OB/*/1/simple_metrics.csv", "re2-ss": f"{DATA}/RE2/RE2-SS/*/1/simple_metrics.csv", "re2-tt": f"{DATA}/RE2/RE2-TT/*/1/simple_metrics.csv"}
for k, pat in pats.items():
    fs = sorted(glob.glob(pat)); df = pd.read_csv(fs[0])
    suffixes = collections.Counter(c.split("_", 1)[1] if "_" in c else c for c in df.columns if c != "time")
    out["tables"][k] = {"file": os.path.relpath(fs[0], DATA), "n_cols": df.shape[1], "n_rows": len(df), "metric_kinds": sorted(suffixes), "has_diskio": any("diskio" in c for c in df.columns)}
json.dump(out, open(sys.argv[1], "w"), indent=1, default=str)
print(json.dumps(out["runs"], indent=0, default=str)[:1500]); print({k: (v["n_cols"], v["n_rows"], v["has_diskio"]) for k, v in out["tables"].items()})
